#!/usr/bin/env bash
# Arr-Stack-Script — interactive installer for a Docker-based ARR media stack.
# Run:  ./install.sh
set -uo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
PROJECT_DIR=$SCRIPT_DIR
ENV_FILE="$PROJECT_DIR/.env"
COMPOSE_FILE="$PROJECT_DIR/docker-compose.yml"

# shellcheck source=lib/common.sh
source "$SCRIPT_DIR/lib/common.sh"
# shellcheck source=lib/system.sh
source "$SCRIPT_DIR/lib/system.sh"
# shellcheck source=lib/services.sh
source "$SCRIPT_DIR/lib/services.sh"

SELECTED=()

# Step 3 — interactive application selection.
select_apps() {
  echo; log "Select applications to install (Enter accepts the default):"
  local key
  for key in "${ALL_SERVICES[@]}"; do
    confirm "  Install ${SVC_LABEL[$key]}?" Y && SELECTED+=("$key")
  done
}

# Step 4 — gather configuration and write .env.
write_env() {
  echo; log "Environment configuration:"
  ask PUID "PUID (user id that owns the files)" "1000"
  ask PGID "PGID (group id)" "1000"
  local tz_default
  tz_default=$(cat /etc/timezone 2>/dev/null) \
    || tz_default=$(readlink -f /etc/localtime 2>/dev/null | sed 's#.*/zoneinfo/##')
  ask TZ "Timezone" "${tz_default:-Etc/UTC}"
  ask CONFIG_ROOT "Config storage path (per-app configs)" "$PROJECT_DIR/config"
  ask MEDIA_ROOT "Media library root (holds tv/movies/music/books)" "/srv/media"
  ask DOWNLOADS_ROOT "Downloads path (shared by download clients)" "/srv/downloads"

  cat > "$ENV_FILE" <<EOF
# Generated by install.sh on $(date)
# Edit and re-run 'docker compose up -d' to apply changes.
PUID=$PUID
PGID=$PGID
TZ=$TZ
CONFIG_ROOT=$CONFIG_ROOT
MEDIA_ROOT=$MEDIA_ROOT
DOWNLOADS_ROOT=$DOWNLOADS_ROOT
EOF
  ok "Wrote $ENV_FILE"
}

# Create config/media directories with correct ownership.
make_dirs() {
  log "Creating config and media directories..."
  local key
  as_root mkdir -p "$MEDIA_ROOT"/{tv,movies,music,books} "$DOWNLOADS_ROOT" "$CONFIG_ROOT"
  for key in "${SELECTED[@]}"; do as_root mkdir -p "$CONFIG_ROOT/$key"; done
  as_root chown -R "$PUID:$PGID" "$CONFIG_ROOT" "$MEDIA_ROOT" "$DOWNLOADS_ROOT" 2>/dev/null \
    || warn "Could not chown all paths to $PUID:$PGID — adjust manually if containers report permission errors."
  ok "Directories ready."
}

# Step 5 — assemble docker-compose.yml from the selected services.
write_compose() {
  local key
  { echo "services:"; for key in "${SELECTED[@]}"; do emit_service "$key"; done; } > "$COMPOSE_FILE"
  ok "Wrote $COMPOSE_FILE"
}

# Best-practice: refuse to launch onto already-bound host ports.
check_ports() {
  have ss || { warn "'ss' not available; skipping port-conflict check."; return 0; }
  local key port busy=0 listening
  listening=$(ss -ltnH 2>/dev/null | awk '{print $4}')
  for key in "${SELECTED[@]}"; do
    port=${SVC_PORT[$key]}
    if grep -qE "[:.]$port\$" <<<"$listening"; then
      warn "Host port $port (needed by $key) is already in use."
      busy=1
    fi
  done
  if ((busy)); then
    confirm "Continue despite port conflict(s)?" N || die "Aborted. Free the ports or edit docker-compose.yml, then re-run."
  fi
}

# Step 6 — launch the stack.
deploy() {
  log "Pulling images and starting containers (this can take a while)..."
  ( cd "$PROJECT_DIR" && $COMPOSE pull && $COMPOSE up -d ) || die "Deployment failed. Check the output above."
}

# Step 8 — post-install checks and access URLs.
post_check() {
  echo; log "Container status:"
  ( cd "$PROJECT_DIR" && $COMPOSE ps )
  local ip key
  ip=$(hostname -I 2>/dev/null | awk '{print $1}'); ip=${ip:-localhost}
  echo; ok "Your services:"
  for key in "${SELECTED[@]}"; do
    printf '   %-12s http://%s:%s\n' "$key" "$ip" "${SVC_PORT[$key]}"
  done
  echo
  warn "First-run notes: set a strong password in each web UI; qBittorrent prints a temporary password in 'docker logs qbittorrent'."
}

main() {
  echo "=============================================="
  echo "         ARR Stack Installer"
  echo "=============================================="
  detect_distro
  install_prereqs
  install_docker
  select_apps
  ((${#SELECTED[@]})) || die "No applications selected — nothing to do."
  write_env
  make_dirs
  write_compose
  check_ports
  echo
  if confirm "Deploy the stack now?" Y; then
    deploy
    post_check
  else
    ok "Setup complete. Launch later with:  cd '$PROJECT_DIR' && $COMPOSE up -d"
  fi
}

main "$@"
