#!/usr/bin/env bash
# Arr-Stack-Script — interactive installer for a Docker-based ARR media stack.
# Run:  ./install.sh
set -uo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
PROJECT_DIR=$SCRIPT_DIR
ENV_FILE="$PROJECT_DIR/.env"
COMPOSE_FILE="$PROJECT_DIR/docker-compose.yml"

# shellcheck source=lib/common.sh
source "$SCRIPT_DIR/lib/common.sh"
# shellcheck source=lib/system.sh
source "$SCRIPT_DIR/lib/system.sh"
# shellcheck source=lib/services.sh
source "$SCRIPT_DIR/lib/services.sh"

SELECTED=()

# Step 3 — interactive application selection.
select_apps() {
  echo; log "Select applications to install (Enter accepts the default):"
  local key
  for key in "${ALL_SERVICES[@]}"; do
    confirm "  Install ${SVC_LABEL[$key]}?" Y && SELECTED+=("$key")
  done
}

# Collect Gluetun VPN settings (only when gluetun is selected).
prompt_vpn() {
  echo; log "Gluetun VPN configuration (routes qBittorrent's traffic):"
  ask VPN_SERVICE_PROVIDER "VPN provider (e.g. mullvad, protonvpn, nordvpn, private internet access)" "mullvad"
  ask VPN_TYPE "VPN type (wireguard or openvpn)" "wireguard"
  WIREGUARD_PRIVATE_KEY=""; WIREGUARD_ADDRESSES=""; OPENVPN_USER=""; OPENVPN_PASSWORD=""
  if [[ $VPN_TYPE == openvpn ]]; then
    ask OPENVPN_USER "OpenVPN username" ""
    ask OPENVPN_PASSWORD "OpenVPN password" ""
  else
    ask WIREGUARD_PRIVATE_KEY "WireGuard private key" ""
    ask WIREGUARD_ADDRESSES "WireGuard address (e.g. 10.64.0.2/32)" ""
  fi
  ask SERVER_COUNTRIES "Preferred server country (optional, e.g. Netherlands)" ""
  [[ -n $WIREGUARD_PRIVATE_KEY || -n $OPENVPN_PASSWORD ]] \
    || warn "No VPN credentials entered — fill them into .env before the tunnel can connect."
}

# Step 4 — gather configuration and write .env.
write_env() {
  echo; log "Environment configuration:"
  ask PUID "PUID (user id that owns the files)" "1000"
  ask PGID "PGID (group id)" "1000"
  local tz_default
  tz_default=$(cat /etc/timezone 2>/dev/null) \
    || tz_default=$(readlink -f /etc/localtime 2>/dev/null | sed 's#.*/zoneinfo/##')
  ask TZ "Timezone" "${tz_default:-Etc/UTC}"
  ask CONFIG_ROOT "Config storage path (per-app configs)" "$PROJECT_DIR/config"
  ask MEDIA_ROOT "Media library root (tv/movies/music/books/audiobooks/podcasts)" "/srv/media"
  ask DOWNLOADS_ROOT "Downloads path (shared by download clients)" "/srv/downloads"

  cat > "$ENV_FILE" <<EOF
# Generated by install.sh on $(date)
# Edit and re-run 'docker compose up -d' to apply changes.
PUID=$PUID
PGID=$PGID
TZ=$TZ
CONFIG_ROOT=$CONFIG_ROOT
MEDIA_ROOT=$MEDIA_ROOT
DOWNLOADS_ROOT=$DOWNLOADS_ROOT
EOF

  if in_selected gluetun; then
    prompt_vpn
    cat >> "$ENV_FILE" <<EOF

# Gluetun VPN (see https://github.com/qdm12/gluetun-wiki for provider specifics)
VPN_SERVICE_PROVIDER=$VPN_SERVICE_PROVIDER
VPN_TYPE=$VPN_TYPE
WIREGUARD_PRIVATE_KEY=$WIREGUARD_PRIVATE_KEY
WIREGUARD_ADDRESSES=$WIREGUARD_ADDRESSES
OPENVPN_USER=$OPENVPN_USER
OPENVPN_PASSWORD=$OPENVPN_PASSWORD
SERVER_COUNTRIES=$SERVER_COUNTRIES
EOF
  fi

  if in_selected homepage; then
    local ip; ip=$(hostname -I 2>/dev/null | awk '{print $1}'); ip=${ip:-localhost}
    ask HOMEPAGE_ALLOWED_HOSTS "Homepage allowed hosts (comma-separated host:port)" "$ip:3000,localhost:3000"
    cat >> "$ENV_FILE" <<EOF

# Homepage — hosts permitted to reach the dashboard (required by recent versions)
HOMEPAGE_ALLOWED_HOSTS=$HOMEPAGE_ALLOWED_HOSTS
EOF
  fi

  ok "Wrote $ENV_FILE"
}

# Create config/media directories with correct ownership.
make_dirs() {
  log "Creating config and media directories..."
  local key
  as_root mkdir -p "$MEDIA_ROOT"/{tv,movies,music,books,audiobooks,podcasts} "$DOWNLOADS_ROOT" "$CONFIG_ROOT"
  for key in "${SELECTED[@]}"; do as_root mkdir -p "$CONFIG_ROOT/$key"; done
  # Pre-create nested config dirs for services whose mounts go below $CONFIG_ROOT/<key>,
  # so they exist with the right owner before Docker bind-mounts them as root.
  in_selected tdarr          && as_root mkdir -p "$CONFIG_ROOT/tdarr"/{server,configs,logs,transcode-cache}
  in_selected audiobookshelf && as_root mkdir -p "$CONFIG_ROOT/audiobookshelf"/{config,metadata}
  as_root chown -R "$PUID:$PGID" "$CONFIG_ROOT" "$MEDIA_ROOT" "$DOWNLOADS_ROOT" 2>/dev/null \
    || warn "Could not chown all paths to $PUID:$PGID — adjust manually if containers report permission errors."
  ok "Directories ready."
}

# Generate a starter Homepage dashboard (only when Homepage is selected) so the
# board isn't empty on first load. Files are staged as the current user, then
# copied in and chowned, since $CONFIG_ROOT may be root-owned.
write_homepage_config() {
  in_selected homepage || return 0
  log "Generating starter Homepage dashboard config..."
  local ip tmp; ip=$(hostname -I 2>/dev/null | awk '{print $1}'); ip=${ip:-localhost}
  tmp=$(mktemp -d)

  cat > "$tmp/settings.yaml" <<EOF
title: ARR Stack
theme: dark
color: slate
headerStyle: clean
EOF

  cat > "$tmp/docker.yaml" <<EOF
my-docker:
  socket: /var/run/docker.sock
EOF

  cat > "$tmp/widgets.yaml" <<EOF
- resources:
    cpu: true
    memory: true
    disk: /
- search:
    provider: duckduckgo
    target: _blank
- datetime:
    text_size: xl
    format:
      timeStyle: short
EOF

  cat > "$tmp/bookmarks.yaml" <<EOF
- Reference:
    - LinuxServer docs:
        - abbr: LS
          href: https://docs.linuxserver.io/
    - TRaSH Guides:
        - abbr: TG
          href: https://trash-guides.info/
EOF

  emit_homepage_services "$ip" > "$tmp/services.yaml"

  as_root mkdir -p "$CONFIG_ROOT/homepage"
  as_root cp "$tmp"/*.yaml "$CONFIG_ROOT/homepage/"
  as_root chown -R "$PUID:$PGID" "$CONFIG_ROOT/homepage"
  rm -rf "$tmp"
  ok "Wrote Homepage config to $CONFIG_ROOT/homepage"
}

# Step 5 — assemble docker-compose.yml from the selected services.
write_compose() {
  local key
  { echo "services:"; for key in "${SELECTED[@]}"; do emit_service "$key"; done; } > "$COMPOSE_FILE"
  ok "Wrote $COMPOSE_FILE"
}

# Best-practice: refuse to launch onto already-bound host ports.
check_ports() {
  have ss || { warn "'ss' not available; skipping port-conflict check."; return 0; }
  local key port busy=0 listening
  listening=$(ss -ltnH 2>/dev/null | awk '{print $4}')
  for key in "${SELECTED[@]}"; do
    port=${SVC_PORT[$key]}
    [[ -z $port ]] && continue   # background services expose no web UI
    if grep -qE "[:.]$port\$" <<<"$listening"; then
      warn "Host port $port (needed by $key) is already in use."
      busy=1
    fi
  done
  if ((busy)); then
    confirm "Continue despite port conflict(s)?" N || die "Aborted. Free the ports or edit docker-compose.yml, then re-run."
  fi
}

# Step 6 — launch the stack.
deploy() {
  log "Pulling images and starting containers (this can take a while)..."
  ( cd "$PROJECT_DIR" && $COMPOSE pull && $COMPOSE up -d ) || die "Deployment failed. Check the output above."
}

# Step 8 — post-install checks and access URLs.
post_check() {
  echo; log "Container status:"
  ( cd "$PROJECT_DIR" && $COMPOSE ps )
  local ip key
  ip=$(hostname -I 2>/dev/null | awk '{print $1}'); ip=${ip:-localhost}
  echo; ok "Your services:"
  for key in "${SELECTED[@]}"; do
    if [[ -z ${SVC_PORT[$key]} ]]; then
      printf '   %-14s (background service, no web UI)\n' "$key"
    else
      printf '   %-14s http://%s:%s\n' "$key" "$ip" "${SVC_PORT[$key]}"
    fi
  done
  echo
  warn "First-run notes: set a strong password in each web UI; qBittorrent prints a temporary password in 'docker logs qbittorrent'."
  in_selected gluetun && warn "Gluetun: confirm the tunnel is up with 'docker logs gluetun' before trusting it; qBittorrent has no connectivity until the VPN connects."
}

main() {
  echo "=============================================="
  echo "         ARR Stack Installer"
  echo "=============================================="
  detect_distro
  install_prereqs
  install_docker
  select_apps
  ((${#SELECTED[@]})) || die "No applications selected — nothing to do."
  USE_GLUETUN=0; in_selected gluetun && USE_GLUETUN=1
  write_env
  make_dirs
  write_compose
  write_homepage_config
  check_ports
  echo
  if confirm "Deploy the stack now?" Y; then
    deploy
    post_check
  else
    ok "Setup complete. Launch later with:  cd '$PROJECT_DIR' && $COMPOSE up -d"
  fi
}

main "$@"
